FROM python:3.11.4

WORKDIR /app

COPY . /app/

RUN pip3 install virtualenv

COPY requirements.txt .

RUN python3 -m venv venv && \
    . venv/bin/activate && \
    venv/bin/python -m pip install --no-cache-dir -U pip && \
    venv/bin/python -m pip install --no-cache-dir -r requirements.txt
CMD ["venv/bin/python", "main.py"]



